- ignore: {name: Avoid lambda using `infix`}
- ignore: {name: Reduce duplication}
- ignore: {name: Use camelCase}
- ignore: {name: Use list literal pattern}
- ignore: {name: Use newtype instead of data}
- ignore: {name: Use uncurry}
- ignore: {name: Redundant pure}
- ignore: {name: Eta reduce}
