name: sxako
version: 0.1.0.0
github: Javran/sxako
license: BSD3
author: Javran Cheng
maintainer: javran.c@gmail.com
copyright: "Copyright: (c) 2019 Javran Cheng"

description: description

dependencies:
- aeson
- attoparsec
- base
- bytestring
- containers
- fixed-vector
- hashable
- mtl
- resourcet
- split
- text
- vector
- writer-cps-mtl
- yaml
- lzma

data-files: 
- data/ChessMerida.svg
- testdata/*.yaml
- testdata/*.yaml.xz

library:
  source-dirs: src
  dependencies:
    - primitive
  ghc-options:
    - -Wall
    - -O2

executables:
  demo:
    main: Main.hs
    source-dirs: exe
    dependencies:
      - sxako
      - colour
      - diagrams-core
      - diagrams-lib
      - diagrams-rasterific
      - SVGFonts
      - typed-process

    ghc-options:
      - -Wall
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  hspec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - sxako
      - QuickCheck
      - hspec
    ghc-options:
      - -Wall
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
