resolver: lts-18.20
packages:
- .

extra-deps:
- SVGFonts-1.8.0.1
- diagrams-core-1.5.0
- diagrams-lib-1.4.5.1
- diagrams-rasterific-1.4.2.2
- active-0.2.0.15
- dual-tree-0.2.3.0
- monoid-extras-0.6.1
